name: ${project.artifactId}
main: net.whg.utils.WraithLib
version: ${project.version}
api-version: 1.17
depends: [PlaceholderAPI]
commands:
  warp:
    description: Creates and manages warp points.
  warppad:
    description: Creates and manages warp pads.
  spawn:
    description: Teleports the player to spawn.
  setspawn:
    description: Assigns the spawn location for the given world.
