name: ${project.artifactId}
main: net.whg.utils.WraithLib
version: ${project.version}
api-version: 1.17
commands:
  whsculpt:
    description: Wraithaven Sculpt commands.
    usage: /whsculpt
  warp:
    description: Creates and manages warp points.
    usage: /warp
  warppad:
    description: Creates and manages warp pads.
    usage: /warppad
  spawn:
    description: Teleports the player to spawn.
    usage: /spawn