name: HavensGames-Utils
main: net.whg.utils.UtilsPlugin
version: 0.1.0
api-version: 1.17
commands:
  whsculpt:
    description: Wraithaven Sculpt commands.
    usage: /whsculpt
  warp:
    description: Creates and manages warp points.
    usage: /warp
  spawn:
    description: Teleports the player to spawn.
    usage: /spawn